version: '3'

services:

  broker-service:
    build:
      context: ./
      dockerfile: broker-service/broker-service.dockerfile
    restart: always
    ports:
      - "9090:90"
    deploy:
      mode: replicated
      replicas: 1
